# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "languages", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  create_table "links", :force => true do |t|
    t.column "from_language_id", :integer,                 :null => false
    t.column "from_rule_id",     :integer,                 :null => false
    t.column "to_language_id",   :integer,                 :null => false
    t.column "to_rule_id",       :integer,                 :null => false
    t.column "argument_mapping", :string,  :default => "", :null => false
    t.column "bidirectional",    :boolean,                 :null => false
  end

  add_index "links", ["from_language_id"], :name => "idx_links_from_language_id"
  add_index "links", ["from_rule_id"], :name => "idx_links_from_rule_id"
  add_index "links", ["to_language_id"], :name => "idx_links_to_language_id"
  add_index "links", ["to_rule_id"], :name => "idx_links_to_rule_id"

  create_table "rules", :force => true do |t|
    t.column "language_id", :integer,                 :null => false
    t.column "rule_text",   :string,  :default => "", :null => false
    t.column "line_number", :integer,                 :null => false
    t.column "arguments",   :integer,                 :null => false
  end

  add_index "rules", ["language_id", "line_number"], :name => "idx_rules_line_number"

end
